name: compiler
version: 0.2.4
author: Christophe Hurpeau <christophe@hurpeau.com>
description: Compile files
homepage: https://github.com/christophehurpeau/dart-compiler
documentation: https://github.com/christophehurpeau/dart-compiler/wiki
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  editor_build: '>=0.0.4 <0.1.0'
  preprocessor: '>=0.1.2 <0.2.0'
  unittest: '>=0.9.0 <0.10.0'
  yaml: '>=0.9.0 <0.10.0'
  dart_events: '>=0.0.1'
  csslib: '>=0.9.1 <0.10.0'