name: compiler
author: Christophe Hurpeau <christophe@hurpeau.com>
version: 0.3.0
homepage: https://github.com/christophehurpeau/dart-compiler
description: Compile files
documentation: http://christophehurpeau.github.io/dart-compiler/docs/
environment:
  sdk: '>=1.1.0 <2.0.0'
dependencies:
  csslib: '>=0.9.2 <0.10.0'
  dart_events: '>=0.0.1'
  editor_build: '>=0.0.4 <0.1.0'
  preprocessor: '>=0.2.0 <0.3.0'
  unittest: '>=0.10.0 <0.11.0'
  yaml: '>=0.9.0 <0.10.0'
